### ISSUE TITLE
Add a notice note to README

### ISSUE THREAD

**Issue by kimchy** [alicegoldfuss/shardnado#1]
Hey Alice!, we chatted here https://github.com/elastic/elasticsearch/issues/18294#issuecomment-218911949 and found out the reasons for shards not being allocated, as allocation was disabled on them.

My concern with this tool is that if someone runs it, it will cause the cluster to not be balanced as it overrides the allocation logic of ES itself. I am opening this issue to brainstorm what we can do? Maybe add a notice to the top of the README about it?

**Comment by alicegoldfuss** [comment]
Hi Shay!

A more intelligent version of this script would take balancing into consideration, but until then I can definitely add a note in the Caveat Emptor section. Good call.

**Comment by kimchy** [comment]
heads up on balancing, it is hard :), probably better let ES try and do it. Btw, in ES, we are working on trying to make what is going on more evident as to why shards are not allocated. In 5.0 we already have a dedicated API for it, but we need to brainstorm into making this even better.

**Comment by alicegoldfuss** [comment]
I like hard problems :)

+1 on making diagnostics easier. Even better if it's easy for plugins to use, since that's where a lot of people look when they get paged.

**Comment by alicegoldfuss** [comment]
Okay, I added a note in the Caveat Emptor section. Thanks again!

**Comment by s1monw** [comment]
> A more intelligent version of this script would take balancing into consideration, but until then I can definitely add a note in the Caveat Emptor section. Good call.

I am confused - why would you need this script at all given that es does balancing already? Apparently the indices that didn't allocate had allocation disabled and that misconfiguration caused this script to happen in the first place, please correct me if I am wrong. So wouldn't be deprecating the tool be the right move rather than rebuilding logic that es has already build in?

**Comment by alicegoldfuss** [comment]
While there was a specific instance of a cluster having allocation turned off (in a sneaky way) that is not the only use case here. My most common experience regarding shard allocation has been an ES cluster with allocation turned on, actively allocating, then giving up with about ~20 shards to go. These shards can be manually assigned without issue. Given conversations I've had on Twitter (and the momentary popularity of this tool) it seems other people have had the exact same issue.

I don't know the root cause of this odd behavior, but I do know this tool is still useful.

**Comment by s1monw** [comment]
> I don't know the root cause of this odd behavior, but I do know this tool is still useful.

I do think this is problematic. From my perspective if you can allocate a shard via the API (what this tool is doing) the cluster can do that too. It can make a much better decision as well where to put the shard. This is also the problem that this too provokes. The cluster will see the shard allocated and will likely relocated it once it's done. Which causes absolutely unnecessary IO, destabilizes the cluster and prevents further allocations. The only reason why this tool can allocate is that it by-passes 2 allocation deciders (both can be set via the API to disable allocations). We consider the APIs called by this tool a last resort and should be used with care, I am concerned this will prevent folks from fixing the actual problem and they won't report bugs but rather run a tool that blindly allocates shards. 

> Given conversations I've had on Twitter (and the momentary popularity of this tool) it seems other people have had the exact same issue.

you mean they disabled allocation and forgot about it? ;)

**Comment by alicegoldfuss** [comment]
I have witnessed clusters with allocation enabled stop allocating shards that I myself can assign via the API. Clearly Elasticsearch does not always work as intended.

> you mean they disabled allocation and forgot about it? ;)

No, that is not what I meant or said. And if you want to keep referring to that issue, let's review:
1. Someone on my team enabled a _deprecated_ setting that disabled allocation on all indexes in a cluster. Why Elasticsearch even had this setting in the first place (while also providing a separate setting to disable allocation for the entire cluster) is beyond me.
2. Because Elasticsearch does not show this deprecated setting in logs or settings readouts, I was not able to diagnose the issue myself.
3. It took 4 Elasticsearch engineers the better part of a day to figure it out.

Instead of continuing to discuss this on a closed issue on a repo with 7 stars that no one will use anyway, how about you reach out to your customers and see if they are having allocation issues? I'm sure they would love to have your help instead of having to resort to a 3am Google search that leads them to my tool.

**Comment by s1monw** [comment]
> Someone on my team enabled a deprecated setting that disabled allocation on all indexes in a cluster. Why Elasticsearch even had this setting in the first place (while also providing a separate setting to disable allocation for the entire cluster) is beyond me.

you can disable allocations on an index or on the entire cluster that is just the granularity we have. The setting was deprecated in order to be replaced by one that doens't have a double negative in it's name. ie naming issue the setting still exists with a different name.

> Because Elasticsearch does not show this deprecated setting in logs or settings readouts, I was not able to diagnose the issue myself.

this has nothing todo with deprecation it was all working as intended. you used an expert API via a tool that by-passes this entirely, we are fixing this.

> It took 4 Elasticsearch engineers the better part of a day to figure it out.

I stated my concerns I hope folks will reach out and help to improve instead of allocating shards them self.
I didn't meant to rant or anything. I think errors are human but we should not build tools that prevent future improvements. I will back off here since I don't think this leads anywhere.

**Comment by alicegoldfuss** [comment]
> you used an expert API via a tool that by-passes this entirely

I'm sorry, I don't know what you mean by this. My tool doesn't use this setting.

> I think errors are human but we should not build tools that prevent future improvements. 

I wrote this tool to help people. And if zero people use it but Elasticsearch improves its diagnostics and monitoring in response, then I would consider that a total win.

>  I will back off here since I don't think this leads anywhere.

Agreed. Thank you for your input.

**Comment by vanga** [comment]
> My most common experience regarding shard allocation has been an ES cluster with allocation turned on, actively allocating, then giving up with about ~20 shards to go. These shards can be manually assigned without issue.

+1 I think

https://discuss.elastic.co/t/unallocated-shards-when-a-node-is-removed/50331

~~but interestingly, when I look at the cluster after a day, shards are allocated now. There is absolutely no traffic for this cluster, to think that shard allocation is getting throttled and I am seeing a delay in allocation.~~
This was a wrong observation

**Comment by s1monw** [comment]
> I'm sorry, I don't know what you mean by this. My tool doesn't use this setting.

the setting `index.routing.allocation.disable_allocation` is ignored if you use the expert `_reroute` API. That was the reason why the tool did allocate it but ES by itself didn't. We are fixing this now to prevent people bypassing their own settings by accident.

> I wrote this tool to help people. And if zero people use it but Elasticsearch improves its diagnostics and monitoring in response, then I would consider that a total win.

my concern is that folks use it for the wrong reason. We have diagnostics in place to that, the `_reroute?explain=true` explains why stuff is not allocated, it also showed that the setting `index.routing.allocation.disable_allocation` was by-passed. If you look close at it is says: `allocation is explicitly ignoring any disabling of allocation`

Also @vanga I think you should check the settings on your indices and cluster, use the explain feature on the `_reroute` API and first find out why before you fix the why. :)

> but interestingly, when I look at the cluster after a day, shards are allocated now. There is absolutely no traffic for this cluster, to think that shard allocation is getting throttled and I am seeing a delay in allocation.
> This was a wrong observation

when ES looses a node it will not immediately allocate shards. it will do after some time. We had bug in that code for instance here:
- https://github.com/elastic/elasticsearch/pull/14494

we also simplified it a lot in 2.2 (https://github.com/elastic/elasticsearch/pull/14808)
All I am saying is that we need to report these issues instead of running a tool Maybe we can make this message very prominent on the readme or whatever but please don't treat this as the holy grail, it's not sorry!

@vanga I subscribed to https://discuss.elastic.co/t/unallocated-shards-when-a-node-is-removed/50331 if you see the issue again please ping me

**Comment by alicegoldfuss** [comment]
I'm unsubscribing from this thread, but feel free to continue discussing.
